import type { DashboardSnapshot, DemoPlaybackStep } from "../types/dashboard";

const baseTime = "2026-05-18T09:00:00.000Z";

export const demoSteps: DemoPlaybackStep[] = [
  {
    id: "prepare",
    title: "Dataset preparation",
    subtitle: "Fashion-MNIST baseline and CIFAR-10-C domain shift preset loaded.",
    focus: "experiment",
  },
  {
    id: "baseline",
    title: "Baseline training",
    subtitle: "Initial stable checkpoint committed on main.",
    focus: "commit",
  },
  {
    id: "incremental",
    title: "Incremental learning",
    subtitle: "Classes 2 and 3 introduced with replay support.",
    focus: "metrics",
  },
  {
    id: "branch",
    title: "Branch evolution",
    subtitle: "Controller creates an experimental branch for safe exploration.",
    focus: "branch",
  },
  {
    id: "shift",
    title: "Domain shift",
    subtitle: "CIFAR-10-C style corruption increases forgetting pressure.",
    focus: "forgetting",
  },
  {
    id: "rollback",
    title: "Rollback recovery",
    subtitle: "Citadel validates rollback to the best stable checkpoint.",
    focus: "rollback",
  },
  {
    id: "override",
    title: "Human override",
    subtitle: "Operator approves a controlled recovery branch.",
    focus: "override",
  },
  {
    id: "summary",
    title: "Final report",
    subtitle: "Metrics, commit graph, branch graph and plots are ready for export.",
    focus: "summary",
  },
];

export const demoSnapshot: DashboardSnapshot = {
  commitGraph: {
    nodes: [
      {
        id: "cmt_baseline",
        branchId: "main",
        checkpointId: "chk_baseline",
        message: "baseline:fashion-0-1",
        createdAt: baseTime,
        metrics: { validationAccuracy: 0.64, forgettingScore: 0 },
      },
      {
        id: "cmt_incremental",
        branchId: "main",
        checkpointId: "chk_incremental",
        message: "incremental:fashion-2-3",
        createdAt: "2026-05-18T09:03:00.000Z",
        metrics: { validationAccuracy: 0.71, forgettingScore: 0.08 },
      },
      {
        id: "cmt_shift",
        branchId: "main",
        checkpointId: "chk_shift",
        message: "domain-shift:cifar10c",
        createdAt: "2026-05-18T09:06:00.000Z",
        metrics: { validationAccuracy: 0.58, forgettingScore: 0.21 },
      },
      {
        id: "cmt_recovered",
        branchId: "main/recovery",
        checkpointId: "chk_recovered",
        message: "rollback-recovery",
        createdAt: "2026-05-18T09:08:00.000Z",
        metrics: { validationAccuracy: 0.76, forgettingScore: 0.07 },
      },
    ],
    edges: [
      { parentId: "cmt_baseline", childId: "cmt_incremental" },
      { parentId: "cmt_incremental", childId: "cmt_shift" },
      { parentId: "cmt_incremental", childId: "cmt_recovered" },
    ],
  },
  branchGraph: {
    nodes: [
      {
        id: "br_main",
        name: "main",
        headCommitId: "cmt_shift",
        baseCommitId: null,
        status: "degraded",
      },
      {
        id: "br_exp",
        name: "main/exp-cmt-incremental",
        headCommitId: "cmt_incremental",
        baseCommitId: "cmt_incremental",
        status: "exploring",
      },
      {
        id: "br_recovery",
        name: "main/recovery",
        headCommitId: "cmt_recovered",
        baseCommitId: "cmt_incremental",
        status: "stable",
      },
    ],
    edges: [
      { parentId: "cmt_incremental", childId: "cmt_shift" },
      { parentId: "cmt_incremental", childId: "cmt_recovered" },
    ],
  },
  metricsTimeline: [
    {
      timestamp: baseTime,
      stageId: "baseline",
      trainLoss: 0.72,
      validationLoss: 0.78,
      trainAccuracy: 0.69,
      validationAccuracy: 0.64,
      forgettingScore: 0,
      oldClassRetention: null,
      newClassAdaptation: 0.81,
    },
    {
      timestamp: "2026-05-18T09:03:00.000Z",
      stageId: "incremental",
      trainLoss: 0.61,
      validationLoss: 0.68,
      trainAccuracy: 0.75,
      validationAccuracy: 0.71,
      forgettingScore: 0.08,
      oldClassRetention: 0.78,
      newClassAdaptation: 0.84,
    },
    {
      timestamp: "2026-05-18T09:06:00.000Z",
      stageId: "domain-shift",
      trainLoss: 0.74,
      validationLoss: 0.91,
      trainAccuracy: 0.69,
      validationAccuracy: 0.58,
      forgettingScore: 0.21,
      oldClassRetention: 0.61,
      newClassAdaptation: 0.72,
    },
    {
      timestamp: "2026-05-18T09:08:00.000Z",
      stageId: "rollback",
      trainLoss: 0.55,
      validationLoss: 0.62,
      trainAccuracy: 0.81,
      validationAccuracy: 0.76,
      forgettingScore: 0.07,
      oldClassRetention: 0.82,
      newClassAdaptation: 0.86,
    },
  ],
  experiments: [
    {
      id: "demo-acn-001",
      name: "ACN Demo: continual adaptation under shift",
      status: "presentation",
      branchName: "main/recovery",
      currentStageId: "rollback",
      currentCommitId: "cmt_recovered",
      bestCommitId: "cmt_recovered",
      updatedAt: "2026-05-18T09:09:00.000Z",
    },
  ],
  controllerDecisions: [
    {
      id: "dec_branch",
      action: "create_experimental_branch",
      confidence: 0.72,
      branchName: "main",
      commitId: "cmt_incremental",
      reasons: ["Validation loss plateau detected.", "Experimental branch preserves stable line."],
      createdAt: "2026-05-18T09:04:00.000Z",
      status: "executed",
    },
    {
      id: "dec_rollback",
      action: "rollback",
      confidence: 0.9,
      branchName: "main",
      commitId: "cmt_shift",
      reasons: ["Validation loss degraded after domain shift.", "Best checkpoint is reachable."],
      createdAt: "2026-05-18T09:07:00.000Z",
      status: "executed",
    },
    {
      id: "dec_override",
      action: "create_experimental_branch",
      confidence: 0.86,
      branchName: "main/recovery",
      commitId: "cmt_recovered",
      reasons: ["Human override accepted for recovery branch promotion."],
      createdAt: "2026-05-18T09:08:30.000Z",
      status: "approved",
    },
  ],
  rollbackHistory: [
    {
      id: "rb_001",
      branchName: "main",
      fromCommitId: "cmt_shift",
      toCommitId: "cmt_incremental",
      actor: "citadel",
      createdAt: "2026-05-18T09:07:30.000Z",
      reason: "Domain shift degraded validation accuracy and forgetting score.",
    },
  ],
  liveLogs: [
    {
      id: "log_001",
      level: "info",
      source: "demo",
      message: "Demo scenario initialized with deterministic preset.",
      createdAt: baseTime,
    },
    {
      id: "log_002",
      level: "warning",
      source: "controller",
      message: "Domain shift detected. Rollback candidate selected.",
      createdAt: "2026-05-18T09:07:00.000Z",
    },
    {
      id: "log_003",
      level: "info",
      source: "citadel",
      message: "Rollback validated and audited.",
      createdAt: "2026-05-18T09:07:30.000Z",
    },
  ],
};
